spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/nomadwear}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:suasenhalocal}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect